# Generated by Django 6.0.2 on 2026-03-03 18:09

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='ник')),
                ('phone_number', models.CharField(blank=True, max_length=64, verbose_name='номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='фамилия')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='био')),
                ('points', models.IntegerField(default=0, verbose_name='баллы')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_path, verbose_name='аватар')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], max_length=10, verbose_name='пол')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='город')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='специальность')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
