# Generated by Django 6.0.2 on 2026-04-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(default=list)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='statistics.userattempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['user', 'quiz'], name='statistics__user_id_e345cc_idx'),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['quiz', 'created_at'], name='statistics__quiz_id_f267c6_idx'),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['user', 'created_at'], name='statistics__user_id_eebe14_idx'),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['is_completed'], name='statistics__is_comp_637c37_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question'], name='statistics__attempt_9ce873_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question'], name='statistics__questio_4a4eee_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['is_correct'], name='statistics__is_corr_70eb24_idx'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_question_per_attempt'),
        ),
    ]
