# Generated by Django 6.0.2 on 2026-03-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(db_index=True, help_text='Unique category code, always stored in uppercase.', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Category name.', max_length=256, unique=True)),
                ('description', models.CharField(blank=True, help_text='Category description.', max_length=512, null=True)),
                ('image', models.ImageField(blank=True, help_text='Category image.', null=True, upload_to='categories/')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='courses_cat_code_3e3673_idx'), models.Index(fields=['name'], name='courses_cat_name_ab7c10_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Course name.', max_length=256, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly slug generated from name.', unique=True)),
                ('description', models.CharField(blank=True, help_text='Course description.', max_length=512, null=True)),
                ('image', models.ImageField(blank=True, help_text='Course image.', null=True, upload_to='courses/')),
                ('is_free', models.BooleanField(default=True, help_text='Whether the course is free.')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Course cost if not free.', max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category this course belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'), models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'), models.Index(fields=['is_free'], name='courses_cou_is_free_827337_idx')],
            },
        ),
    ]
