# Generated by Django 6.0.2 on 2026-03-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title.', max_length=256)),
                ('content', models.JSONField(default=dict, help_text='Lesson content in TipTap editor format (JSON).')),
                ('image', models.ImageField(blank=True, help_text='Main lesson image.', null=True, upload_to='lessons/')),
                ('is_draft', models.BooleanField(default=True, help_text='Whether the lesson is in draft state.')),
                ('auto_test', models.BooleanField(default=False, help_text='Whether the lesson has auto-testing enabled.')),
                ('priority', models.IntegerField(default=1, help_text='Order of the lesson within the course.')),
                ('course', models.ForeignKey(help_text='Course this lesson belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file for the lesson.', upload_to='lesson_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this image was uploaded.')),
                ('lesson', models.ForeignKey(help_text='Lesson this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'priority'], name='lessons_les_course__4d234c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_draft'], name='lessons_les_is_draf_f7a4f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'priority'), name='unique_lesson_priority_per_course'),
        ),
        migrations.AddIndex(
            model_name='lessonimage',
            index=models.Index(fields=['lesson'], name='lessons_les_lesson__321a22_idx'),
        ),
    ]
